name: Building Documentation

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: test_aiida
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
      rabbitmq:
        image: rabbitmq:3.7-management
        ports:
        - 5672:5672
        - 15672:15672

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install pandoc
      run: |
        sudo apt-get install --no-install-recommends pandoc graphviz
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-deps -r doc/requirements.txt
        verdi quicksetup --non-interactive --profile tests --email test@user.com --first-name Test --last-name Test --institution Test --db-backend core.psql_dos
    - name: Build documentation
      env:
        MP_API_KEY: ${{ secrets.MP_API_KEY }}
        MP_OPENAPI_KEY: ${{ secrets.MP_OPENAPI_KEY }}
      run: |
        cd doc/
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: aim2dat/aim2dat.github.io
        publish_dir: ./doc/build/html
